### ISSUE TITLE
Multiple MAVs explore the same environment using GBplanner separately

### ISSUE THREAD

**Issue by Rye450** [unr-arl/gbplanner_ros#18]
Hi @[MihirDharmadhikari](https://github.com/MihirDharmadhikari)
Recently, I'm trying to add another MAV in simulation and then two MAVs can explore the same environment separately(from different starting point).
The link of launch file which I'm using is as follows:
https://github.com/Rye450/gbplanner_test/blob/1583caafbd70fc93400b224723fe6b64b8da025d/byl_two.launch

However,the belowing terminal output shows that the second MAV seems to plan much slower than the first one:
![two_terminal_output](https://user-images.githubusercontent.com/45511401/155050522-65cdff3c-dc23-49e1-a687-6a3678c6b97e.png)

The planner of the first MAV has already planned for 100 times,while the planner of the second MAV has only planned for 5 times.
The second MAV stays still all the time while the first MAV has already moved for a long distance in gazebo as follows:
![two_gazebo](https://user-images.githubusercontent.com/45511401/155050506-b45187b1-144c-43da-affa-5d673c63c6bd.jpg)

I have already checked the tf tree,there are transformations between the sensor frame of two MAVs and the fixed frame.
![two_tf_tree](https://user-images.githubusercontent.com/45511401/155050616-cd2bfc72-3184-47be-97c3-0346c637b3bc.png)

Could you tell me what's wrong with my launch file?

Looking forward to your reply!

**Comment by MihirDharmadhikari** [comment]
Hi @Rye450 ,

Sorry for the late reply. 
Have you tried triggering the planner for each robot individually? Run the same launch file as you have but trigger only one robot at a time and see if this persists.
Also, another observation is that you will have to run the gbplanner and PCI for each robot in a different namespace otherwise the same service will go to both robots causing problems.
Let me know if this works.

Best,
Mihir
